[project]
name = "dlclient"
version = "1.0.0"

dependencies = [
    "opencv-python==4.8.1.78",
    "numpy==1.26.0",
    "whiptail-dialogs==0.4.0"
]

[tool.setuptools]
packages = ["dlclient"]

[project.scripts]
dlclient_cli = "dlclient.cli_client:main"
