[project]
name = "dlclient"
version = "1.0.0"

dependencies = [
    "opencv-python",
    "numpy",
    "whiptail-dialogs"
]

[tool.setuptools]
packages = ["dlclient"]

[project.scripts]
dlclient_cli = "dlclient.cli_client:main"
