- name: MobileNetv2.7
  url: https://github.com/onnx/models/raw/main/vision/classification/mobilenet/model/mobilenetv2-7.onnx
  preprocessing: None
  input_type: "image"
  postprocessing: None
  output_type: "text"

